### ISSUE TITLE
Create User Fails

### ISSUE THREAD

**Issue by uolter** [nicolaiarocci/flask-sentinel#1]
Hi Nicola,

I think you have something wrong in the management.html template.

When you add new user the form post says: <form method="post" action="/">
But it looks like there is no action for "/"
I changed the html at line 35 with <form method="post" action="/oauth/management"> and it behaves well.

Cheers

**Comment by nicolaiarocci** [comment]
Thanks for reporting this. Should now be fixed on development branch.
