### ISSUE TITLE
Pypi package not updated (0.0.5 vs 0.0.6)

### ISSUE THREAD

**Issue by XaviTorello** [nicolaiarocci/flask-sentinel#17]
The last changes has not been uploaded to PyPi.

The current version of this lib is 0.0.6, but at Pypi there is the 0.0.5 version.

https://pypi.python.org/pypi/Flask-Sentinel
```
Package Index > Flask-Sentinel > 0.0.5

Flask-Sentinel 0.0.5

Download Flask-Sentinel-0.0.5.tar.gz

OAuth2 Provider for Flask applications.

OAuth2 Provider currently supporting the Resource Owner Password Credentials Grant as described in Section 1.3.3 of RFC 6749.

Powered by Flask-OAuthlib, Redis and MongoDB.
```

Please, can it be updated? @nicolaiarocci 

I suggest to integrate Travis or Drone to ensure automatic pip deployment while tagging new versions or merging to master.

Related to #16

**Comment by XaviTorello** [comment]
#### Temporal workaround

Until this issue is closed, use the code of the develop branch (default branch of the repo) instead of the package name at requirements file

```
https://github.com/nicolaiarocci/flask-sentinel/archive/develop.zip
```

**Comment by nicolaiarocci** [comment]
Yup if you look at the [changelog](https://github.com/nicolaiarocci/flask-sentinel/blob/develop/CHANGES) v0.0.6 is still unreleased.
