### ISSUE TITLE
user hash encoding with python 3

### ISSUE THREAD

**Issue by djbrd-sourcefabric** [nicolaiarocci/flask-sentinel#19]
I notice that this bug (line 108 of data.py) has been fixed in the devel branch. I have installed the package with pip. Will you be updating it any time soon? Thanks

**Comment by nicolaiarocci** [comment]
Soon! This week, hopefully.

**Comment by djbrd-sourcefabric** [comment]
This week maybe?

**Comment by nicolaiarocci** [comment]
Sorry for the delay. It's released now.

**Comment by djbrd-sourcefabric** [comment]
Thank you!
