### ISSUE TITLE
Forced debug mode

### ISSUE THREAD

**Issue by stt** [nicolaiarocci/flask-sentinel#4]
Hi, forcing debug on should probably not be here?

https://github.com/nicolaiarocci/flask-sentinel/blob/904a2dba5311252936c992e57e05b7b0c6f29410/flask_sentinel/flask_sentinel.py#L27

(It caused various issues, some other extensions modify their behavior when "debugging")

**Comment by nicolaiarocci** [comment]
Of course. Thanks!
